name: Inbound Sellers
favicon: null
layout_spectrum: 0.7811746823135763
typography_spectrum: 0.5744122939649969
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#353e51'
    - '#f2dcd5'
    - '#d27d26'
    - '#a01d22'
  brandStrength: 0.680365429725498
  lightness: 0.028759539127349854
  saturation: 0.5056714368984103
  rhythmicContrast: 0.0759420501999557
purpose: []
